# Generated by Django 5.1.15 on 2026-08-31 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('test_type', models.CharField(choices=[('weighing_performance', 'Weighing Performance'), ('eccentricity', 'Eccentricity'), ('repeatability', 'Repeatability'), ('discrimination', 'Discrimination'), ('sensitivity', 'Sensitivity'), ('tare', 'Tare Device'), ('creep', 'Creep / Time Dependence'), ('zero_return', 'Zero Return'), ('temperature', 'Temperature'), ('tilt', 'Tilt'), ('power_supply', 'Power Supply Variation'), ('durability', 'Durability'), ('span_stability', 'Span Stability'), ('zero_tracking', 'Zero Tracking')], max_length=30)),
                ('test_point_load', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('indicated_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('reference_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('correction', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('trial_number', models.PositiveIntegerField(default=1)),
                ('direction', models.CharField(blank=True, choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing')], max_length=20)),
                ('timestamp_minutes', models.DecimalField(blank=True, decimal_places=1, help_text='Minutes elapsed, for creep tests (0, 15, 30)', max_digits=6, null=True)),
            ],
            options={
                'ordering': ['test_type', 'trial_number', 'test_point_load'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('session_date', models.DateField()),
                ('temperature_start', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_end', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('barometric_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('verification_type', models.CharField(choices=[('initial', 'Initial'), ('subsequent', 'Subsequent')], default='initial', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('overall_verdict', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_applicable', 'Not Applicable')], max_length=20, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_sessions', to='instruments.instrument')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_sessions', to='laboratory.laboratory')),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('test_type', models.CharField(choices=[('weighing_performance', 'Weighing Performance'), ('eccentricity', 'Eccentricity'), ('repeatability', 'Repeatability'), ('discrimination', 'Discrimination'), ('sensitivity', 'Sensitivity'), ('tare', 'Tare Device'), ('creep', 'Creep / Time Dependence'), ('zero_return', 'Zero Return'), ('temperature', 'Temperature'), ('tilt', 'Tilt'), ('power_supply', 'Power Supply Variation'), ('durability', 'Durability'), ('span_stability', 'Span Stability'), ('zero_tracking', 'Zero Tracking')], max_length=30)),
                ('test_point_load', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('computed_error', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('mpe_applicable', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('compliance_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_applicable', 'Not Applicable')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('trial_number', models.PositiveIntegerField(default=1)),
                ('remarks', models.TextField(blank=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='testing.testobservation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testing.testsession')),
            ],
            options={
                'ordering': ['test_type', 'trial_number', 'test_point_load'],
            },
        ),
        migrations.AddField(
            model_name='testobservation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='testing.testsession'),
        ),
    ]
