# Generated by Django 5.1.15 on 2026-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_add_evaluation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='expanded_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Expanded measurement uncertainty U (k=2)', max_digits=15, null=True),
        ),
    ]
