# Generated by Django 5.1.15 on 2026-09-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_testresult_expanded_uncertainty'),
    ]

    operations = [
        migrations.AddField(
            model_name='testobservation',
            name='delta_load',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Additional load ΔL at which the indication changed over to I + d (changeover-point / half-division method, R 76-2 A.4.4.3). When set, the error is computed as E = I + 0.5d − ΔL − L.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testobservation',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ambient temperature (°C) at which this observation was taken', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testsession',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testsession',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
