# Generated by Django 5.1.15 on 2026-08-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100)),
                ('accuracy_class', models.CharField(choices=[('I', 'Class I (Special)'), ('II', 'Class II (High)'), ('III', 'Class III (Medium)'), ('IIII', 'Class IIII (Ordinary)')], max_length=4)),
                ('max_capacity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('min_capacity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('verification_scale_interval_e', models.DecimalField(decimal_places=6, max_digits=15)),
                ('actual_scale_interval_d', models.DecimalField(decimal_places=6, max_digits=15)),
                ('num_scale_intervals_n', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('mg', 'Milligram'), ('g', 'Gram'), ('kg', 'Kilogram'), ('t', 'Tonne'), ('ct', 'Metric Carat')], default='kg', max_length=5)),
                ('tare_device_type', models.CharField(choices=[('none', 'None'), ('non_additive', 'Non-Additive (Subtractive)'), ('additive', 'Additive'), ('both', 'Both')], default='none', max_length=20)),
                ('max_additive_tare', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('max_safe_load', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('is_multi_interval', models.BooleanField(default=False)),
                ('multi_interval_config', models.JSONField(blank=True, help_text='[{"max": 2000, "e": 1}, {"max": 5000, "e": 2}]', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_test', 'Under Test')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('manufacturer', 'serial_number'), name='unique_serial_per_manufacturer')],
            },
        ),
    ]
