# Generated by Django 5.1.15 on 2026-09-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('jurisdiction', models.CharField(default='MINISTRY OF CONSUMER AFFAIRS, FOOD & PUBLIC DISTRIBUTION', max_length=255)),
                ('report_prefix', models.CharField(default='NAWI', max_length=20)),
                ('doc_control_number', models.CharField(default='LM-FMT-NAWI-01', max_length=50)),
                ('doc_issue_number', models.CharField(default='01', max_length=10)),
                ('doc_rev_number', models.CharField(default='00', max_length=10)),
                ('default_remarks', models.JSONField(blank=True, default=list)),
                ('logo_data_uri', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Organisation settings',
                'verbose_name_plural': 'Organisation settings',
            },
        ),
    ]
