# Generated by Django 5.1.15 on 2026-09-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_orgsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='doc_issue_date',
            field=models.CharField(default='01.01.2026', max_length=20),
        ),
    ]
